[package]
name = "bff"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version="0.33.2", features=["serde-serialize"] }
rmp = "0.8.14"
faer = "0.21.4"
rmp-serde = "1.3.0"
serde = { version = "1.0.217", features = ["derive"] }

[dev-dependencies]
approx = "0.5.1"
zip = "2.2.2"
